### ISSUE TITLE
work only on host, try set chance 100%

### ISSUE THREAD

**Issue by rogedkone** [Electric131/IsThisTheWayICame#1] opened 2023-12-26 17:35 UTC
work only on host, try set chance 100% but friends still spawn near true fire exit

**Comment by Electric131** [comment] 2023-12-26 21:59
Does this happen on March? March is a known issue due to it having multiple exits and will be fixed in the next patch.

**Comment by rogedkone** [comment] 2023-12-26 22:05
Experimental, Titan, Also March

**Comment by Electric131** [comment] 2023-12-26 22:07
This error should only happen on maps with more than one exit, could you try to provide a clip of the bug and/or reproduction steps?

**Comment by rogedkone** [comment] 2023-12-26 22:12
Hm... This problem may be related to the mimic mod config?

It takes two to repeat. Both have both parameters set to 100 in the config. The map is experimental. The second player (not the host) enters the bunker and exits. On the minimap, I see how the player first teleports to a non-real exit, but then quickly move to the real exit

**Comment by Electric131** [comment] 2023-12-26 22:15
You could be right with the first part, the mod will resort back to the real exit if no mimics spawn.

**Comment by Electric131** [comment] 2023-12-27 01:30
Thanks for bringing this to my attention, this revealed a much more major bug where the normal doors would spawn if you made "change on use" false. The reason for this is the random number generator being called after the swapping. Both bugs are fixed in the newest version of the mod, soon to be released.

**Closed as completed by Electric131** 2023-12-27 01:30 UTC
Labels: bug
